version: '3.8'

services:
  server:
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_HOST=$POSTGRES_HOST
      - DATABASE_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
